name: walle
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-edge.df2b0426dfd8385088114c1b80a5936135a2ee90 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  http: ^0.13.5
  process_run: ^0.12.3+2
